### ISSUE TITLE
Error in running make all command patched OQS openssl fork

### ISSUE THREAD

**Issue by sandilya761** [wolfSSL/osp#131]
I am following all the instructions as given [here](https://github.com/wolfSSL/osp/tree/master/oqs). I am getting following errors after running the final command i.e, `make all`.

![image](https://user-images.githubusercontent.com/57587519/216682378-3b2fe59e-cda5-4371-9870-dd58d684c4a7.png)

**Comment by anhu** [comment]
I have just re-tried the steps outlined in the page in the section titied "OpenSSL" you referenced and cannot reproduce your errors. That said, this indicates that various SPHINCS paarameter sets were not properly patched.  Was there any output that indicated error when you did this: 

```
patch -p1 < /path/to/osp/oqs/openssl-sphincs.patch
```

Also note that there is a section called "Generating the Patch" .  You do not need to follow those instructions.  That is not part of what you are supposed to do. 

Warm regards, Anthony

**Comment by NomanNasirMinhas** [comment]
@anhu I am facing the same issue. I have attached the screenshots of the `history` as well as the start of the error in `make all` command. You can check the output of `history` command to see if all the steps were followed properly. The OpenSSL version is `OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)`. Also, even though this screenshot is of error on raspberry pi, I faced the same error on Ubuntu as well.
![2](https://github.com/wolfSSL/osp/assets/28532113/c9aaf52d-c378-415d-8482-50c7481e8d18)
![Capture](https://github.com/wolfSSL/osp/assets/28532113/c57a6a66-607a-4baf-a9f1-b48a234afea8)
